[package]
name = "smallvil"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing = "0.1.37"
bitflags = "2.2.1"
thiserror = "1"
xcursor = "0.3.3"

[dependencies.smithay]
version = "0.7.0"
default-features = false
features = [
    "backend_winit",
    "backend_libinput",
    "backend_udev",
    "backend_drm",
    "backend_gbm",
    "backend_egl",
    "backend_session_libseat",
    "renderer_gl",
    "renderer_multi",
    "use_system_lib",
    "wayland_frontend",
    "desktop",
]

[dependencies.smithay-drm-extras]
version = "0.1.0"
default-features = false
